backend:
  name: github
  repo: yanluoxingchen/yanluoxingchen.github.io
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "预览图", name: "image", widget: "image", required: false }
      - { label: "外部链接", name: "link", widget: "string", required: false }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "pages"
    label: "页面"
    files:
      - label: "简历"
        name: "resume"
        file: "content/resume.md"
        fields:
          - { label: "内容", name: "body", widget: "markdown" }
